# -*- coding: utf-8 -*-
"""主要工作界面的统一窗口尺寸。"""

APP_SURFACE_MIN_WIDTH = 1120
APP_SURFACE_MIN_HEIGHT = 720
APP_SURFACE_DEFAULT_WIDTH = 1280
APP_SURFACE_DEFAULT_HEIGHT = 820

APP_SURFACE_MIN_SIZE = (APP_SURFACE_MIN_WIDTH, APP_SURFACE_MIN_HEIGHT)
APP_SURFACE_DEFAULT_SIZE = (APP_SURFACE_DEFAULT_WIDTH, APP_SURFACE_DEFAULT_HEIGHT)
